image:
  repository: ghcr.io/aresiusxp/porkbun-dns-update/porkbun-dns-update
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

cronjob:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  restartPolicy: OnFailure

secretName: porkbun-dns-update
dnsRecords:
  - "test1"
  - "test2"
dnsDomain: "example.com"
dnsTtl: 300
