name: Tests and build container image

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*" # Trigger on version tags like v1.0.0
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover tests

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    # Only run on a push event for a tag starting with 'v'
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract tag name
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Publish Image
        id: publish
        uses: matootie/github-docker@v3.0.0
        with:
          accessToken: ${{ secrets.PACKAGES_WRITE }}
          tag: ${{ steps.extract_tag.outputs.tag }}

      - name: Print Full Image URL
        run: echo ${{ steps.publish.outputs.imageURL }}:${{ steps.extract_tag.outputs.tag }}
